create-countries-json:
	node country-profanity.js > country-profanity.json

create-artists-json:
	node artists-genres.js > artist-genres.json

create-lyrics-json:
	node word-profanity.js > word-profanity.json